import { useEffect, useRef, useState } from 'react';
import { useApp } from '../../app/AppContext';
import { selectSelectedImage } from '../../app/selectors';
import { canvasToDataUrl, cloneCanvas, hexToRgb, srcToCanvas } from '../../image-processing/canvasImage';
export function ImageAdjustModal(){const{state,dispatch}=useApp();const image=selectSelectedImage(state);const preview=useRef<HTMLCanvasElement>(null);const base=useRef<HTMLCanvasElement|null>(null);const[mode,setMode]=useState<'replace'|'binarize'|'crop'>('replace');const[source,setSource]=useState('#ffffff'),[target,setTarget]=useState('#c42026'),[tolerance,setTolerance]=useState(40),[threshold,setThreshold]=useState(128),[crop,setCrop]=useState(0);
 useEffect(()=>{if(!image)return;void srcToCanvas(image.src).then(c=>{base.current=c;redraw()})},[image?.id]);
 function redraw(){if(!base.current||!preview.current)return;let c=cloneCanvas(base.current),ctx=c.getContext('2d')!;if(mode==='replace'){const d=ctx.getImageData(0,0,c.width,c.height),a=d.data,s=hexToRgb(source),t=hexToRgb(target);for(let i=0;i<a.length;i+=4){const dist=Math.hypot(a[i]!-s.r,a[i+1]!-s.g,a[i+2]!-s.b);if(dist<=tolerance){a[i]=t.r;a[i+1]=t.g;a[i+2]=t.b}}ctx.putImageData(d,0,0)}else if(mode==='binarize'){const d=ctx.getImageData(0,0,c.width,c.height),a=d.data;for(let i=0;i<a.length;i+=4){const v=.299*a[i]!+.587*a[i+1]!+.114*a[i+2]!,n=v>=threshold?255:0;a[i]=a[i+1]=a[i+2]=n}ctx.putImageData(d,0,0)}else if(crop>0){const inset=Math.round(Math.min(c.width,c.height)*crop/100),n=document.createElement('canvas');n.width=Math.max(1,c.width-inset*2);n.height=Math.max(1,c.height-inset*2);n.getContext('2d')!.drawImage(c,inset,inset,n.width,n.height,0,0,n.width,n.height);c=n}preview.current.width=c.width;preview.current.height=c.height;preview.current.getContext('2d')!.drawImage(c,0,0)}
 useEffect(redraw,[mode,source,target,tolerance,threshold,crop]);if(!image)return null;
 const apply=()=>{const c=preview.current!;dispatch({type:'UPDATE_IMAGE',imageId:image.id,patch:{src:canvasToDataUrl(c),mimeType:'image/png',width:c.width,height:c.height}});dispatch({type:'SET_MODAL',modal:null})};
 return <div className="modal-backdrop"><div className="editor-modal"><header><div><strong>画像補正</strong><small>ローカル処理・適用前プレビュー</small></div><button onClick={()=>dispatch({type:'SET_MODAL',modal:null})}>×</button></header><div className="modal-body two-column"><aside className="modal-controls"><div className="segmented-actions"><button className={mode==='replace'?'is-active':''} onClick={()=>setMode('replace')}>色置換</button><button className={mode==='binarize'?'is-active':''} onClick={()=>setMode('binarize')}>2階調</button><button className={mode==='crop'?'is-active':''} onClick={()=>setMode('crop')}>トリミング</button></div>{mode==='replace'&&<><label>置換元<input type="color" value={source} onChange={e=>setSource(e.target.value)}/></label><label>置換後<input type="color" value={target} onChange={e=>setTarget(e.target.value)}/></label><label>許容範囲 {tolerance}<input type="range" min="0" max="180" value={tolerance} onChange={e=>setTolerance(+e.target.value)}/></label></>}{mode==='binarize'&&<label>しきい値 {threshold}<input type="range" min="0" max="255" value={threshold} onChange={e=>setThreshold(+e.target.value)}/></label>}{mode==='crop'&&<label>四辺の切り取り {crop}%<input type="range" min="0" max="40" value={crop} onChange={e=>setCrop(+e.target.value)}/></label>}</aside><div className="modal-canvas-wrap"><canvas ref={preview}/></div></div><footer><button onClick={()=>dispatch({type:'SET_MODAL',modal:null})}>キャンセル</button><button className="primary-button" onClick={apply}>画像へ適用</button></footer></div></div>}
