import { useEffect, useRef, useState } from 'react';
import { useApp } from '../../app/AppContext';
import { selectSelectedImage } from '../../app/selectors';
import { canvasToDataUrl, cloneCanvas, srcToCanvas } from '../../image-processing/canvasImage';
type Mode='erase'|'paint'|'blur';
export function RetouchModal(){const{state,dispatch}=useApp();const image=selectSelectedImage(state);const canvasRef=useRef<HTMLCanvasElement>(null),original=useRef<HTMLCanvasElement|null>(null),drawing=useRef(false),last=useRef<{x:number;y:number}|null>(null),history=useRef<string[]>([]);const[mode,setMode]=useState<Mode>('erase'),[size,setSize]=useState(40),[opacity,setOpacity]=useState(100),[color,setColor]=useState('#ffffff'),[blur,setBlur]=useState(10),[before,setBefore]=useState(false);
 useEffect(()=>{if(!image)return;void srcToCanvas(image.src).then(c=>{original.current=c;const v=canvasRef.current!;v.width=c.width;v.height=c.height;v.getContext('2d')!.drawImage(c,0,0);history.current=[v.toDataURL()]})},[image?.id]);if(!image)return null;
 const point=(e:React.PointerEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect();return{x:(e.clientX-r.left)*e.currentTarget.width/r.width,y:(e.clientY-r.top)*e.currentTarget.height/r.height}};
 const stroke=(a:{x:number;y:number},b:{x:number;y:number})=>{const c=canvasRef.current!,ctx=c.getContext('2d')!;ctx.save();ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=size;ctx.globalAlpha=opacity/100;if(mode==='erase'){ctx.globalCompositeOperation='destination-out';ctx.strokeStyle='#000'}else if(mode==='paint'){ctx.globalCompositeOperation='source-over';ctx.strokeStyle=color}else{const temp=cloneCanvas(c),t=temp.getContext('2d')!;t.filter=`blur(${blur}px)`;t.drawImage(c,0,0);ctx.beginPath();ctx.arc(b.x,b.y,size/2,0,Math.PI*2);ctx.clip();ctx.drawImage(temp,0,0);ctx.restore();return}ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.restore()};
 const undo=()=>{if(history.current.length<=1)return;history.current.pop();const i=new Image();i.onload=()=>{const c=canvasRef.current!,ctx=c.getContext('2d')!;ctx.clearRect(0,0,c.width,c.height);ctx.drawImage(i,0,0)};i.src=history.current.at(-1)!};
 const apply=()=>{const c=canvasRef.current!;dispatch({type:'UPDATE_IMAGE',imageId:image.id,patch:{src:canvasToDataUrl(c),mimeType:'image/png'}});dispatch({type:'SET_MODAL',modal:null})};
 return <div className="modal-backdrop"><div className="editor-modal retouch-modal"><header><div><strong>画像修正</strong><small>消去・単色塗り・ぼかし</small></div><button onClick={()=>dispatch({type:'SET_MODAL',modal:null})}>×</button></header><div className="modal-body two-column"><aside className="modal-controls"><div className="segmented-actions"><button className={mode==='erase'?'is-active':''} onClick={()=>setMode('erase')}>消去</button><button className={mode==='paint'?'is-active':''} onClick={()=>setMode('paint')}>塗る</button><button className={mode==='blur'?'is-active':''} onClick={()=>setMode('blur')}>ぼかす</button></div>{mode==='paint'&&<label>色<input type="color" value={color} onChange={e=>setColor(e.target.value)}/></label>}<label>ブラシサイズ {size}px<input type="range" min="4" max="160" value={size} onChange={e=>setSize(+e.target.value)}/></label><label>不透明度 {opacity}%<input type="range" min="10" max="100" value={opacity} onChange={e=>setOpacity(+e.target.value)}/></label>{mode==='blur'&&<label>ぼかし強度 {blur}px<input type="range" min="2" max="30" value={blur} onChange={e=>setBlur(+e.target.value)}/></label>}<button className="secondary-button" onClick={undo}>モーダル内で元に戻す</button><button className="secondary-button" onPointerDown={()=>setBefore(true)} onPointerUp={()=>setBefore(false)} onPointerLeave={()=>setBefore(false)}>長押しで修正前</button></aside><div className="modal-canvas-wrap"><canvas ref={canvasRef} style={{visibility:before?'hidden':'visible'}} onPointerDown={e=>{drawing.current=true;last.current=point(e);e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(!drawing.current||!last.current)return;const p=point(e);stroke(last.current,p);last.current=p}} onPointerUp={e=>{drawing.current=false;last.current=null;history.current.push(e.currentTarget.toDataURL())}}/>{before&&original.current&&<img className="before-image" src={original.current.toDataURL()} />}</div></div><footer><button onClick={()=>dispatch({type:'SET_MODAL',modal:null})}>キャンセル</button><button className="primary-button" onClick={apply}>元画像へ適用</button></footer></div></div>}
