import { ArrowRight, Circle, Crop, Eraser, Hand, ImageMinus, MessageSquare, MousePointer2, Paintbrush, Palette, Pencil, Square, Tag, Type } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useApp } from '../app/AppContext';
import { selectSelectedImage, selectSelectedShape } from '../app/selectors';
import type { ToolId } from '../document/types';
const tools:{id:ToolId;label:string;icon:typeof MousePointer2}[]=[{id:'select',label:'選択',icon:MousePointer2},{id:'pan',label:'移動',icon:Hand},{id:'pen',label:'ペン',icon:Pencil},{id:'text',label:'テキスト',icon:Type},{id:'rect',label:'四角',icon:Square},{id:'ellipse',label:'円',icon:Circle},{id:'arrow',label:'矢印',icon:ArrowRight},{id:'speech-bubble',label:'吹出',icon:MessageSquare},{id:'color-tag',label:'色タグ',icon:Tag}];
export function ToolPanel(){const{state,dispatch}=useApp();const image=selectSelectedImage(state),shape=selectSelectedShape(state);const[opacity,setOpacity]=useState(100);useEffect(()=>{if(image)setOpacity(Math.round(image.opacity*100))},[image]);
 return <aside className="side-panel tool-panel"><section className="panel-section"><div className="section-heading"><span>ツール</span><small>選択してキャンバス操作</small></div><div className="tool-grid">{tools.map(t=>{const I=t.icon;return <button key={t.id} className={`tool-button ${state.activeTool===t.id?'is-active':''}`} onClick={()=>dispatch({type:'SET_TOOL',tool:t.id})}><I size={19}/><span>{t.label}</span></button>})}</div></section>
 <section className="panel-section"><div className="section-heading"><span>描画設定</span></div><div className="settings-stack"><label className="field-row">色<input type="color" value={state.toolOptions.color} onChange={e=>dispatch({type:'SET_TOOL_OPTIONS',patch:{color:e.target.value}})}/></label><div className="field-group"><div className="field-label-row"><label>線の太さ</label><output>{state.toolOptions.lineWidth}px</output></div><input type="range" min="1" max="20" value={state.toolOptions.lineWidth} onChange={e=>dispatch({type:'SET_TOOL_OPTIONS',patch:{lineWidth:+e.target.value}})}/></div><div className="segmented-actions"><button className={state.toolOptions.lineStyle==='solid'?'is-active':''} onClick={()=>dispatch({type:'SET_TOOL_OPTIONS',patch:{lineStyle:'solid'}})}>実線</button><button className={state.toolOptions.lineStyle==='dashed'?'is-active':''} onClick={()=>dispatch({type:'SET_TOOL_OPTIONS',patch:{lineStyle:'dashed'}})}>破線</button></div></div></section>
 <section className="panel-section panel-section-grow"><div className="section-heading"><span>選択中</span><small>{image?'画像':shape?'図形':'未選択'}</small></div>{image?<div className="settings-stack"><strong>{image.name}</strong><div className="field-group"><div className="field-label-row"><label>透明度</label><output>{opacity}%</output></div><input type="range" min="0" max="100" value={opacity} onChange={e=>setOpacity(+e.target.value)} onPointerUp={()=>dispatch({type:'UPDATE_IMAGE',imageId:image.id,patch:{opacity:opacity/100}})}/></div><button className="secondary-button" onClick={()=>dispatch({type:'SET_MODAL',modal:'adjust'})}><Palette size={17}/>画像補正</button><button className="secondary-button" onClick={()=>dispatch({type:'SET_MODAL',modal:'retouch'})}><Paintbrush size={17}/>画像修正</button><button className="danger-button" onClick={()=>dispatch({type:'REMOVE_IMAGE',imageId:image.id})}><ImageMinus size={17}/>画像を削除</button></div>:shape?<div className="settings-stack"><strong>{shape.type}</strong><label className="field-row">色<input type="color" value={shape.color} onChange={e=>dispatch({type:'UPDATE_SHAPE',shapeId:shape.id,patch:{color:e.target.value}})}/></label>{(shape.type==='text'||shape.type==='speech-bubble')&&<textarea value={shape.text??''} onChange={e=>dispatch({type:'UPDATE_SHAPE',shapeId:shape.id,patch:{text:e.target.value}})}/>}<button className="danger-button" onClick={()=>dispatch({type:'REMOVE_SHAPE',shapeId:shape.id})}><Eraser size={17}/>図形を削除</button></div>:<div className="panel-empty"><Crop size={23}/><p>画像または図形を選択</p></div>}</section></aside>}
